### ISSUE TITLE
crash "'utf16' codec can't decode byte" on some files

### ISSUE THREAD

**Issue by core-code** [nicfit/eyeD3#105]
i'm getting this on some files with 0.8.2

Uncaught exception: 'utf16' codec can't decode byte 0xfe in position 2: truncated data

eyed3:ERROR: 'utf16' codec can't decode byte 0xfe in position 2: truncated data
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/Library/Python/2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/Library/Python/2.7/site-packages/eyed3/utils/__init__.py", line 91, in walk
    handler.handleFile(os.path.abspath(path))
  File "/Library/Python/2.7/site-packages/eyed3/plugins/classic.py", line 457, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/Library/Python/2.7/site-packages/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/eyed3/core.py", line 78, in load
    return mp3.Mp3AudioFile(path, tag_version)
  File "/Library/Python/2.7/site-packages/eyed3/mp3/__init__.py", line 172, in __init__
    core.AudioFile.__init__(self, path)
  File "/Library/Python/2.7/site-packages/eyed3/core.py", line 256, in __init__
    self._read()
  File "/Library/Python/2.7/site-packages/eyed3/mp3/__init__.py", line 178, in _read
    tag_found = self._tag.parse(file_obj, self._tag_version)
  File "/Library/Python/2.7/site-packages/eyed3/id3/tag.py", line 101, in parse
    tag_found, padding = self._loadV2Tag(fileobj)
  File "/Library/Python/2.7/site-packages/eyed3/id3/tag.py", line 133, in _loadV2Tag
    self.extended_header)
  File "/Library/Python/2.7/site-packages/eyed3/id3/frames.py", line 1418, in parse
    frame = createFrame(tag_header, frame_header, data)
  File "/Library/Python/2.7/site-packages/eyed3/id3/frames.py", line 1518, in createFrame
    frame.parse(data, frame_header)
  File "/Library/Python/2.7/site-packages/eyed3/id3/frames.py", line 274, in parse
    self.text = decodeUnicode(self.data[1:], self.encoding)
  File "/Library/Python/2.7/site-packages/eyed3/id3/frames.py", line 1534, in decodeUnicode
    return unicode(bites, codec).rstrip("\x00")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode byte 0xfe in position 2: truncated data

**Comment by nicfit** [comment]
Most likely the string is encoded incorrenctling in the file, but need files to test.  Please attatch test cases. Zip/tar them to allow github to accept.

**Comment by core-code** [comment]
i'm not keen on sharing copyrighted material publicly. i've mailed travis@pobox.com with a link to test files exhibiting bugs 101, 104 & 105.
