### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by fluidblue** [nicfit/eyeD3#112]
Hello,

when installing eyed3 on macOS 10.12.6 with

    pip3 install eyed3

the installation completes, but afterwards when importing eyed3 with

    import eyed3

in python3, the following exception occurs:

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/Users/name/.virtualenvs/id3/lib/python3.6/site-packages/eyed3/__init__.py", line 35, in <module>
	    from .utils.log import log                                            # noqa
	  File "/Users/name/.virtualenvs/id3/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 27, in <module>
	    import magic
	  File "/Users/name/.virtualenvs/id3/lib/python3.6/site-packages/magic.py", line 176, in <module>
	    raise ImportError('failed to find libmagic.  Check your installation')
	ImportError: failed to find libmagic.  Check your installation

Edit: Installing eyed3 version 0.8 works, whereas 0.8.1, 0.8.2 and 0.8.3 show the above exception.

**Comment by nicfit** [comment]
libmagic now a dependency, see #91 for installation instr. for macOS
