### ISSUE TITLE
0.8.3/python3: plugin display with ID3 tag COMM (comment): TypeError: must be str, not CommentFrame

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#117]
Using **0.8.3** over **python3** to display comments, with this:

`eyeD3 --plugin display --pattern '%comment%'`

With any file containing the ID3 tag COMM, such as this one, for example:

```
/home/paulo/tmp/Atrium Musicæ de Madrid/Monodia Cortesana Medieval • Música Arábigo-Andaluza/11 Ondas do mar de Vigo.mp3                                                              [ 2.60 MB ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 01:55	MPEG1, Layer III	[ ~188 kb/s @ 44100 Hz - Joint stereo ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.3:
title: Ondas do mar de Vigo
artist: Atrium Musicæ de Madrid
album: Monodia Cortesana Medieval • Música Arábigo-Andaluza
album artist: José Luis Ochoa de Olza, Orchesta Marroquí de Tetuán (Abdessadak Chkara)
recording date: 1969
eyed3.id3:WARNING: Non standard genre name: Medieval
track: 11		genre: Medieval (id None)
Comment: [Description: ] [Lang: XXX]
Cantigas de amigo
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

it chokes with this error:

```
Uncaught exception: must be str, not CommentFrame

eyed3:ERROR: must be str, not CommentFrame
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 91, in walk
    handler.handleFile(os.path.abspath(path))
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 1046, in handleFile
    print(self.__pattern.output_for(self.audio_file),
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 47, in output_for
    output += sub_pattern.output_for(audio_file)
TypeError: must be str, not CommentFrame
```

**Comment by nicfit** [comment]
Fixed in https://github.com/nicfit/eyeD3/commit/2d70df48ffeebc91c80e65fd9476054405ee0397

**Comment by marcelpaulo** [comment]
What can I say ?! Thanks a lot, @nicfit, for fixing this ! Have just tested it, no issues anymore.
