### ISSUE TITLE
Using an unknown tag in --pattern (plugin display) throws: display.PatternCompileException: Unknown tag

### ISSUE THREAD

**Issue by marcelpaulo** [nicfit/eyeD3#118]
I was plugging an eyeD3 command into a quodlibet plugin, made a mistake which resulted in using a unknown tag in `--pattern` (plugin display):

`eyeD3 --plugin display --pattern '%TAG%' Atrium\ Musicæ\ de\ Madrid/`

causing eyeD3 to throw an uncaught exception:

```
Unknown tag 'TAG'
Uncaught exception: Unknown tag 'TAG'

eyed3:ERROR: Unknown tag 'TAG'
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 65, in __compile
    self.sub_patterns = self.__compile_asts(asts)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 73, in __compile_asts
    patterns.append(self.__compile_ast(ast))
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 84, in __compile_ast
    parameters)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 106, in __create_complex_pattern
    class_name + "'")
display.PatternCompileException: Unknown tag 'TAG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 103, in walk
    handler.handleFile(f)
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 1046, in handleFile
    print(self.__pattern.output_for(self.audio_file),
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 46, in output_for
    for sub_pattern in self.sub_patterns or []:
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 52, in __get_sub_patterns
    self.__compile()
  File "/home/paulo/.local/lib/python3.6/site-packages/eyed3/plugins/display.py", line 68, in __compile
    raise PatternCompileException(parsing_error.message)
display.PatternCompileException: Unknown tag 'TAG'

```

I would imagine this will follow the same route as #114: catching the exception and showing an error message.

Running **0.8.3** 54b4735118060c26501bff1d6a10b9c3566dd8ae with python 3.6.3 on Xubuntu 17.10

**Comment by marcelpaulo** [comment]
Working spotlessly, have just tested it !
