### ISSUE TITLE
windows 10: ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by MichaelDBA** [nicfit/eyeD3#136]
I installed libmagic and python-magic before installing eydD3 but still get this error.  I am using python 2.7 and eyeD3  0.8.4.  Here is the entire error message:
```
c:\Python27\Lib\site-packages>eyeD3
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\eyeD3.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\eyed3\__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "c:\python27\lib\site-packages\eyed3\utils\__init__.py", line 27, in <module>
    import magic
  File "c:\python27\lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation


```

It looks like I need **magic1.dll**, but why wasn't it already downloaded when I installed libmagic?  So where would I get this DLL do download it manually, assuming I have correctly identified the problem?

**Comment by nicfit** [comment]
@MichaelDBA , this is likely a dup of #132. Reopen if you are still having problems.
