### ISSUE TITLE
Doesn't work anymore on Google Play Music Files

### ISSUE THREAD

**Issue by iFuckedIggyAzalea** [nicfit/eyeD3#153]
Hi there, when I try to remove all id3 tags from google play music files (which I bought) with eyeD3 --remove-frame PRIV or eyeD3 --remove-all, then I get the message that there are no id3 tags to remove.
Is it due to a new algorithm from google or did I do something wrong?

**Comment by nicfit** [comment]
I have no idea. What does `eyeD3 -l debug ...` look like?

**Comment by AndreasWidmer** [comment]
Same here! Is there any solution?

```
eyeD3 -l debug --remove-all test.mp3

eyed3:DEBUG: command line args: Namespace(album=None, album_artist=None, artist=None, backup=False, bpm=None, comments=[], composer=None, config=None, convert_version=None, debug_pdb=False, debug_profile=False, disc_num=None, disc_total=None, encoding_date=None, excludes=None, force_update=False, fs_encoding='utf-8', genre=None, images=[], list_plugins=False, log_level=[['debug']], lyrics=[], max_padding=True, no_color=False, no_config=False, non_std_genres=False, objects=[], orig_release_date=None, paths=['test.mp3'], play_count=None, plugin=<eyed3.plugins.classic.ClassicPlugin object at 0x101ca7dd0>, popularities=[], preserve_file_time=False, publisher=None, quiet=False, recording_date=None, release_date=None, release_year=None, remove_all=True, remove_all_comments=False, remove_all_images=False, remove_all_lyrics=False, remove_all_objects=False, remove_comment=[], remove_fids=[], remove_image=[], remove_lyrics=[], remove_object=[], remove_popularity=[], remove_v1=False, remove_v2=False, rename_pattern=None, simple_comment=None, tag_version=(3, None, None), tagging_date=None, text_encoding=None, text_frames=[], title=None, track=None, track_offset=None, track_total=None,unique_file_ids=[], url_frames=[], user_text_frames=[], user_url_frames=[], verbose=False, write_images_dir=None, write_objects_dir=None)
eyed3:DEBUG: plugin is: <eyed3.plugins.classic.ClassicPlugin object at 0x101ca7dd0>
eyed3.core:DEBUG: Loading file: test.mp3
eyed3.core:DEBUG: File mime-type: audio/mpeg
eyed3.mp3:DEBUG: mp3 header search starting @ 0
eyed3.mp3.headers:DEBUG: MPEG audio version: 1.0
eyed3.mp3.headers:DEBUG: MPEG audio layer: III
eyed3.mp3.headers:DEBUG: MPEG sampling frequency: 44100
eyed3.mp3.headers:DEBUG: MPEG bit rate: 320
eyed3.mp3.headers:DEBUG: MPEG channel mode: Stereo
eyed3.mp3.headers:DEBUG: MPEG channel mode extension: 0
eyed3.mp3.headers:DEBUG: MPEG CRC error protection: False
eyed3.mp3.headers:DEBUG: MPEG original: 0
eyed3.mp3.headers:DEBUG: MPEG copyright: 0
eyed3.mp3.headers:DEBUG: MPEG private bit: 0
eyed3.mp3.headers:DEBUG: MPEG padding: 0
eyed3.mp3.headers:DEBUG: MPEG emphasis: None
eyed3.mp3.headers:DEBUG: MPEG frame length: 1044
eyed3.mp3:DEBUG: mp3 header fffbe000 found at position: 0x0
eyed3.mp3.headers:DEBUG: Info header detected @ 24
eyed3.mp3.headers:DEBUG: Info header flags: 0xf
eyed3.mp3.headers:DEBUG: Info numFrames: 14912
eyed3.mp3.headers:DEBUG: Info numBytes: 15582562
eyed3.mp3.headers:DEBUG: Info TOC (100 bytes): PRESENT
eyed3.mp3.headers:DEBUG: Lame info tag found at position 156
eyed3.mp3.headers:WARNING: Lame tag CRC check failed
eyed3.mp3.headers:DEBUG: Lame Encoder Version: LAME3.98
eyed3.mp3.headers:DEBUG: Lame info tag version: 0
eyed3.mp3.headers:DEBUG: Lame VBR method: Constant Bitrate
eyed3.mp3.headers:DEBUG: Lame Lowpass filter value: 20500 Hz
eyed3.mp3.headers:DEBUG: Lame Peak signal amplitude: 1.13381028 (+1.1 dB)
eyed3.mp3.headers:DEBUG: Lame Radio Replay Gain: -10.4 dB (Set automatically)
eyed3.mp3.headers:DEBUG: Lame Encoding flags: --nspsytune --nssafejoint
eyed3.mp3.headers:DEBUG: Lame ATH type: 4
eyed3.mp3.headers:DEBUG: Lame Bitrate (Constant): 255
eyed3.mp3.headers:DEBUG: Lame Encoder delay: 576 samples
eyed3.mp3.headers:DEBUG: Lame Encoder padding: 1052 samples
eyed3.mp3.headers:DEBUG: Lame Source Sample Frequency: 44.1 kHz
eyed3.mp3.headers:DEBUG: Lame Unwise settings used: False
eyed3.mp3.headers:DEBUG: Lame Stereo mode: Joint
eyed3.mp3.headers:DEBUG: Lame Noise Shaping: 1
eyed3.mp3.headers:DEBUG: Lame MP3 Gain: 0 (+0.0 dB)
eyed3.mp3.headers:DEBUG: Lame Bitrate (Constant): 320
eyed3.mp3.headers:DEBUG: Lame Surround Info: None
eyed3.mp3.headers:DEBUG: Lame Preset: CBR 320
eyed3.mp3.headers:DEBUG: Lame Music Length: 0 bytes
eyed3.mp3.headers:DEBUG: Lame Music CRC: 0000
eyed3.mp3.headers:DEBUG: Lame Info Tag CRC: 0000
test.mp3                                                          [ 14.86 MB ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Uncaught exception: 'NoneType' object has no attribute 'file_info'

eyed3:ERROR: 'NoneType' object has no attribute 'file_info'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/eyed3/main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "/Library/Python/2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/Library/Python/2.7/site-packages/eyed3/utils/__init__.py", line 95, in walk
    handler.handleFile(os.path.abspath(path))
  File "/Library/Python/2.7/site-packages/eyed3/plugins/classic.py", line 467, in handleFile
    if self.handleRemoves(self.audio_file.tag):
  File "/Library/Python/2.7/site-packages/eyed3/plugins/classic.py", line 785, in handleRemoves
    tag.file_info.name, remove_version,
AttributeError: 'NoneType' object has no attribute 'file_info'
```


MacOs High Sierra, eyeD3 --version 0.8.5

**Update: Looks like a MacOS problem! Works on debian without problems**

**Comment by karanrajpal14** [comment]
I'm facing the same issue as well. Has anyone found a fix for this?

**Comment by nicfit** [comment]
> Update: Looks like a MacOS problem! Works on debian without problems
 
Closing this issue until more info is available, or it occurs in 0.9 eyeD3
