### ISSUE TITLE
Error when using --remove-all on files created by abcde

### ISSUE THREAD

**Issue by mohahn** [nicfit/eyeD3#183]
```
abc@a95646cc1cec:/$ uname -a
Linux a95646cc1cec 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 x86_64 x86_64 GNU/Linux
abc@a95646cc1cec:/$ eyeD3 -v
Nothing to do
abc@a95646cc1cec:/$ eyeD3 --version
0.8.5
```

MP3s are created by `abcde` without any tags.

```
$ eyeD3 '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Time: 01:11     MPEG1, Layer III        [ ~238 kb/s @ 44100 Hz - Joint stereo ]

No ID3 v1.x/v2.x tag found!
```

By default, I'm settings tags in combination with `--remove-all` because sometimes there are MP3s created by other tools in this folder too. But this fails:

```
$ eyeD3 --remove-all -a 'Zauberwelt der Märchen' -A 'Drei Haselnüsse für Aschenbrödel' -t 'Titellied' '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Uncaught exception: 'NoneType' object has no attribute 'file_info'

eyed3:ERROR: 'NoneType' object has no attribute 'file_info'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 95, in walk
    handler.handleFile(os.path.abspath(path))
  File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/classic.py", line 467, in handleFile
    if self.handleRemoves(self.audio_file.tag):
  File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/classic.py", line 785, in handleRemoves
    tag.file_info.name, remove_version,
AttributeError: 'NoneType' object has no attribute 'file_info'
```

What does work, is calling the above command without `--remove-all` first and second time with `--remove-all` and it just works:

```
$ eyeD3 -a 'Zauberwelt der Märchen' -A 'Drei Haselnüsse für Aschenbrödel' -t 'Titellied' '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Setting artist: Zauberwelt der Märchen
Setting album: Drei Haselnüsse für Aschenbrödel
Setting title: Titellied
Time: 01:11     MPEG1, Layer III        [ ~238 kb/s @ 44100 Hz - Joint stereo ]

ID3 v2.4:
title: Titellied
artist: Zauberwelt der Märchen
album: Drei Haselnüsse für Aschenbrödel
track:
Writing ID3 version v2.4

$ eyeD3 --remove-all -a 'Zauberwelt der Märchen' -A 'Drei Haselnüsse für Aschenbrödel' -t 'Titellied' '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Removing ID3 v1.x and/or v2.x tag: SUCCESS
Setting artist: Zauberwelt der Märchen
Setting album: Drei Haselnüsse für Aschenbrödel
Setting title: Titellied
Time: 01:11     MPEG1, Layer III        [ ~238 kb/s @ 44100 Hz - Joint stereo ]

ID3 v2.4:
title: Titellied
artist: Zauberwelt der Märchen
album: Drei Haselnüsse für Aschenbrödel
track:
Writing ID3 version v2.4
```

What also fails is when removing all tags multiple times:

```
$ eyeD3 --remove-all '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Removing ID3 v1.x and/or v2.x tag: SUCCESS
Time: 01:11     MPEG1, Layer III        [ ~238 kb/s @ 44100 Hz - Joint stereo ]

No ID3 v1.x/v2.x tag found!
$ eyeD3 --remove-all '/audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3'
.../audio/Zauberwelt der Märchen/Drei Haselnüsse für Aschenbrödel/01. Titellied.mp3[ 2.04 MB ]

Uncaught exception: 'NoneType' object has no attribute 'file_info'

eyed3:ERROR: 'NoneType' object has no attribute 'file_info'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "/usr/local/lib/python2.7/dist-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 95, in walk
    handler.handleFile(os.path.abspath(path))
  File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/classic.py", line 467, in handleFile
    if self.handleRemoves(self.audio_file.tag):
  File "/usr/local/lib/python2.7/dist-packages/eyed3/plugins/classic.py", line 785, in handleRemoves
    tag.file_info.name, remove_version,
AttributeError: 'NoneType' object has no attribute 'file_info'
```

BTW: If I let `abcde` tag these files, it's executing

```
tagtrack-mp3-01 nice -n 10 eyeD3 --encoding utf16 -A Drei Haselnüsse für Aschenbrödel -a Zauberwelt der Märchen -t Titellied -G 255 -n 01 -N 26 --text-frame=TDRC:2014 /tmp/abcde.b10edc1a/track01.mp3
tagtrack-01 true
```
But eyeD3 does not find any tag inside file. But the main problem for me is, that eyeD3 seems to crash on `--remove-all` if there are no tags.

**Comment by nicfit** [comment]
Thanks for reporting this @mohahn
