### ISSUE TITLE
WARNING:eyed3.id3.frames:Frame 'IPLS' is not yet supported, using raw Frame to parse

### ISSUE THREAD

**Issue by gboysko** [nicfit/eyeD3#203]
I'm getting these warnings with newer MP3s (purchased from eMusic). I'm using `eyeD3` inside this Github app: https://github.com/gboysko/shuffle-db which invokes the `load` API.

Some files have this warning as well:

```
WARNING:eyed3.core:Invalid date: 0707
```
I'm wondering if these this frame (`IPLS`) will be supported soon and whether it prevents a `load` from succeeding. Further, I'm not sure the date warning is being reported properly. For example, if I list the file on the command line, I see:

```
eyed3.id3.tag:WARNING: Invalid v2.3 TYER, TDAT, or TIME frame: Invalid date string: 2017--
```

**Comment by nicfit** [comment]
> WARNING:eyed3.core:Invalid date: 0707

0707 is definitely a bogus date.

IPLS is an ID3 v2.3 frame that is currently unsupported by eyeD3. It is replaced by TMCL and TIPL in ID3 v2.4.

I would expect eyed3.load to succeed. Is it?

**Comment by gboysko** [comment]
Hey @nicfit, It does appear that `load` succeeds. I was initially concerned about whether the messages would impede the loading process, but as long as I don't rely on `IPLS` than I should be okay.

I set logging to the `ERROR` level to hide it.

I will look closer into the handling of dates to see if something is erroneous.

**Comment by nicfit** [comment]
Thanks for checking @gboysko

**Comment by abakum** [comment]
> IPLS is an ID3 v2.3 frame that is currently unsupported by eyeD3. It is replaced by TMCL and TIPL in ID3 v2.4.

```
python -m eyed3.main --to-v2.3 --text-frame TIPL:"foo" "bar.mp3"
...
Setting TIPL text frame to 'foo'
...
Writing ID3 version v2.3
Uncaught exception: Unable to covert the following frames to version v2.3: TIPL

eyed3:ERROR: Unable to covert the following frames to version v2.3: TIPL
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python2.7\site-packages\eyed3/main.py", line 281, in <module>
    retval = mainFunc(args, config)
  File "C:\msys64\mingw64\lib\python2.7\site-packages\eyed3/main.py", line 49, in main
    fs_encoding=args.fs_encoding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/utils/__init__.py", line 75, in walk
    handler.handleFile(os.path.abspath(path))
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/plugins/classic.py", line 485, in handleFile
    max_padding=max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 774, in save
    self._saveV2Tag(version, encoding, max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 968, in _saveV2Tag
    max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 871, in _render
    version)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 1122, in _convertFrames
    unconverted))
TagException: Unable to covert the following frames to version v2.3: TIPL
````
```
python -m eyed3.main --to-v2.3 --text-frame TMCL:"foo" "bar.mp3"
...
Setting TMCL text frame to 'foo'
...
Writing ID3 version v2.3

eyed3:ERROR: Unable to covert the following frames to version v2.3: TMCL
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python2.7\site-packages\eyed3/main.py", line 281, in <module>
    retval = mainFunc(args, config)
  File "C:\msys64\mingw64\lib\python2.7\site-packages\eyed3/main.py", line 49, in main
    fs_encoding=args.fs_encoding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/utils/__init__.py", line 75, in walk
    handler.handleFile(os.path.abspath(path))
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/plugins/classic.py", line 485, in handleFile
    max_padding=max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 774, in save
    self._saveV2Tag(version, encoding, max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 968, in _saveV2Tag
    max_padding)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 871, in _render
    version)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/eyed3/id3/tag.py", line 1122, in _convertFrames
    unconverted))
TagException: Unable to covert the following frames to version v2.3: TMCL
```

**Comment by nicfit** [comment]
@abakum , yea.. Neither of those frames are part of ID3 2.3 spec, so they cannot get converted .

**Comment by abakum** [comment]
Thanks, nicfit. Please tell how to use raw frame of eyeD3 to set IPLS in ID3 2.3
