### ISSUE TITLE
does not work with python 3.7.4

### ISSUE THREAD

**Issue by webmobiles** [nicfit/eyeD3#341]
I've run my code, and fails on the import line:  import eyed3

python3 ./mp3titleToFiles.py

```

Traceback (most recent call last):
  File "./mp3titleToFiles.py", line 4, in <module>
    import eyed3
  File "/usr/local/lib/python3.7/site-packages/eyed3/__init__.py", line 32, in <module>
    from .utils.log import log                                          # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/eyed3/utils/__init__.py", line 27, in <module>
    import magic
  File "/usr/local/lib/python3.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

```

**Comment by nicfit** [comment]
@webmobiles What's your OS? Windows is picky about libmagic This is saying that the libmagic library (C lib) is not installed. LIkely not specific to Python 3.7

**Comment by webmobiles** [comment]
it's solved, i've had to install:

brew install libmagic

maybe it can be added on the guide.
