### ISSUE TITLE
"Uncaught exception: Unable to convert the following frames to version v2.3: GRP1"

### ISSUE THREAD

**Issue by kforney** [nicfit/eyeD3#357]
OS: Arch Linux
Installed eyeD3 through pip.
Command run: `python -m eyed3.main --remove-frame PRIV ./ `

I was attempting to run eyeD3 to clean my music library of tags from Google Play Music.  However, it hit a snag on one file, and threw this error.

Here's the output from that track:

ID3 v2.3:
title: AFTERGLOW
artist: Silentroom
album: UNDERVEIL THE EXTRA
album artist: Unisphere
composer: Toby Fox
recording date: 2017
track: 16/16		genre: Soundtrack (id 24)
disc: 1/1
OTHER Image: [Size: 131467 bytes] [Type: image/png]
Description: 

Writing ID3 version v2.3
Uncaught exception: Unable to convert the following frames to version v2.3: GRP1

eyed3:ERROR: Unable to convert the following frames to version v2.3: GRP1
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/eyed3/main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "/usr/lib/python3.7/site-packages/eyed3/main.py", line 49, in main
    fs_encoding=args.fs_encoding)
  File "/usr/lib/python3.7/site-packages/eyed3/utils/__init__.py", line 127, in walk
    handler.handleFile(f)
  File "/usr/lib/python3.7/site-packages/eyed3/plugins/classic.py", line 526, in handleFile
    max_padding=max_padding)
  File "/usr/lib/python3.7/site-packages/eyed3/id3/tag.py", line 814, in save
    self.version = version
  File "/usr/lib/python3.7/site-packages/eyed3/id3/tag.py", line 225, in version
    converted = self._convertFrames(std, non, v)
  File "/usr/lib/python3.7/site-packages/eyed3/id3/tag.py", line 1197, in _convertFrames
    unconverted))
eyed3.id3.tag.TagException: Unable to convert the following frames to version v2.3: GRP1

**Comment by gboysko** [comment]
FWIW, I have the same problem, but with the `RGAD` frame. I'm using v0.8.11.

**Comment by nicfit** [comment]
Added GRP1 support in 642d897

**Comment by awsms** [comment]
> FWIW, I have the same problem, but with the `RGAD` frame. I'm using v0.8.11.

Same here, still not supported?

**Comment by nicfit** [comment]
0.8.x is quite old, but the problem MAY be the same.  Give a newer version a shot. An workaround is to remove the RGAD frames, lossy... and then convert.
