### ISSUE TITLE
Windows unicode paths not working

### ISSUE THREAD

**Issue by Christilut** [nicfit/eyeD3#368]
When I run this command (notice the `ō`, which is [this char](https://www.fileformat.info/info/unicode/char/014d/index.htm)):
```
eyeD3.exe -P lameinfo -l debug C\:/Users/Christiaan/Music/test\ tracks/Kaikō\ -\ Djedjotronic.mp3
```
I get the following error:
```
eyed3:DEBUG: command line args: Namespace(backup=False, config=None, debug_pdb=False, debug_profile=False, excludes=None, fs_encoding='utf-8', list_plugins=False, log_level=[['debug']], no_color=False, no_config=False, paths=['C:/Users/Christiaan/Music/test tracks/Kaik\u014d - Djedjotronic.mp3'], plugin=<lameinfo.LameInfoPlugin object at 0x000001AEB8785D08>, quiet=False)
eyed3:DEBUG: plugin is: <lameinfo.LameInfoPlugin object at 0x000001AEB8785D08>
eyed3.core:DEBUG: Loading file: C:\Users\Christiaan\Music\test tracks\Kaik\u014d - Djedjotronic.mp3
eyed3.core:DEBUG: File mime-type: cannot open `C:\Users\Christiaan\Music\test tracks\Kaik\305\215 - Djedjotronic.mp3' (No such file or directory)
Uncaught exception: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>

eyed3:ERROR: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
Traceback (most recent call last):
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\site-packages\eyed3\main.py", line 277, in _main
    retval = mainFunc(args, config)
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\site-packages\eyed3\main.py", line 49, in main
    fs_encoding=args.fs_encoding)
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\site-packages\eyed3\utils\__init__.py", line 108, in walk
    handler.handleFile(os.path.abspath(path))
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\site-packages\eyed3\plugins\lameinfo.py", line 51, in handleFile
    self.printHeader(f)
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\site-packages\eyed3\plugins\lameinfo.py", line 45, in printHeader
    Fore.RESET))
  File "c:\users\christiaan\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
```

I'm using git bash and Windows 10.
eyeD3 version: 0.8.10

**Comment by nicfit** [comment]
Thanks for reporting @Christilut .  I cannot reproduce on linux. My test was pretty contrived tho, without your mp3 I just named a file `Kaikō - Djedjotronic.mp3`. It is happening while trying to determine mimetype it seems. Any chance you can get the alpha version of eyeD3 a try?  It uses completely different mime-type logic.4

`pip install eyeD3==0.9a3`

**Comment by Christilut** [comment]
With the alpha version it shows me debug info and then has the same error:

```
... more above here...
eyed3.mp3:DEBUG: mp3 header fffb9000 found at position: 0xefbd
eyed3.mp3.headers:DEBUG: b'Info' header detected @ 24
eyed3.mp3.headers:DEBUG: b'Info' header flags: 0xf
eyed3.mp3.headers:DEBUG: b'Info' numFrames: 10985
eyed3.mp3.headers:DEBUG: b'Info' numBytes: 4591698
eyed3.mp3.headers:DEBUG: b'Info' TOC (100 bytes): PRESENT
Uncaught exception: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>

eyed3:ERROR: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
Traceback (most recent call last):
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\main.py", line 262, in _main
    retval = mainFunc(args, config)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\main.py", line 36, in main
    fs_encoding=args.fs_encoding)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\utils\__init__.py", line 71, in walk
    handler.handleFile(os.path.abspath(path))
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\plugins\lameinfo.py", line 33, in handleFile
    self.printHeader(f)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\plugins\lameinfo.py", line 27, in printHeader
    Fore.RESET))
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
```

```
$ ./eyeD3.exe --version
0.9a3
```

**Comment by nicfit** [comment]
Hey @Christilut , thanks for trying the new version.
If you can, give this a shot... In lameinfo.py change the first `print` to `printMsg`

I'm working up a patch for this but don't have Windows to test on. BTW, this s likely due to you terminals default encoding being [cp1252](https://en.wikipedia.org/wiki/Windows-1252) and that encoding us not capable of converting \u014d.  i.e. you might get success by changing the default terminal encoding; but `printMsg` has fallback logic for this issue.

**Comment by Christilut** [comment]
```
    def printHeader(self, filePath):
        from stat import ST_SIZE
        fileSize = os.stat(filePath)[ST_SIZE]
        size_str = formatSize(fileSize)
        printMsg("\n%s\t%s[ %s ]%s" % (boldText(os.path.basename(filePath),
                                             HEADER_COLOR()),
                                    HEADER_COLOR(), size_str,
                                    Fore.RESET))
        print("-" * 79)
```

Same error

**Comment by Christilut** [comment]
In `cmd` it does work, even without the change to `print`.

In `git bash` which is mintty it doesn't work.

**Comment by nicfit** [comment]
Ok, that change based on TERM is what I suspect. Although, I'd like to see the fallack that printMsg provides work.. can you post the stack trace that happens in mintty?

**Comment by Christilut** [comment]
```
Uncaught exception: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>

eyed3:ERROR: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
Traceback (most recent call last):
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\utils\console.py", line 421, in printMsg
    fp.write("%s\n" % s)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\main.py", line 262, in _main
    retval = mainFunc(args, config)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\main.py", line 36, in main
    fs_encoding=args.fs_encoding)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\utils\__init__.py", line 71, in walk
    handler.handleFile(os.path.abspath(path))
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\plugins\lameinfo.py", line 33, in handleFile
    self.printHeader(f)
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\plugins\lameinfo.py", line 27, in printHeader
    Fore.RESET))
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\site-packages\eyed3\utils\console.py", line 423, in printMsg
    fp.write("%s\n" % str(s.encode("utf-8", "replace"), "utf-8"))
  File "c:\users\Christiaan\.virtualenvs\eyed3-Christiaan-4pqwibwm\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 6: character maps to <undefined>
```

**Comment by cheitzig** [comment]
I realized this might be similar to the issue I just posted. Suggestion for you to try, @Christilut 

At the cmd prompt, try setting an environment variable for PYTHONIOENCODING=utf8. (i.e.,:
`set PYTHONIOENCODING=utf8`

**Comment by Christilut** [comment]
Thanks! That seemed to fix it
