### ISSUE TITLE
Add pathlib to requirements

### ISSUE THREAD

**Issue by venkatesh-1729** [nicfit/eyeD3#43]
ImportError: No module named pathlib

**Comment by nicfit** [comment]
What version of eyeD3 and Python?

**Comment by richardthornton** [comment]
I am using Python 2.7.6 and eyeD3 0.8 and am experiencing the same issue:

```
Traceback (most recent call last):
  File "/usr/local/bin/eyed3", line 7, in <module>
    from eyed3.main import _main
  File "/usr/local/lib/python2.7/dist-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 23, in <module>
    import pathlib
```

Installing with `pip install pathlib` solves the problem.

**Comment by CoderYugansh** [comment]
I also cannot used the library , can't import got the same error
Traceback (most recent call last):
  File "/usr/local/bin/eyed3", line 7, in <module>
    from eyed3.main import _main
  File "/usr/local/lib/python2.7/dist-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 23, in <module>
    import pathlib
