### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by spvkgn** [nicfit/eyeD3#56]
Does 0.8 version work with unicode characters? This error not occurred with 0.7.11.
```
eyeD3 01.\ Discothèque.mp3 
Uncaught exception: 'ascii' codec can't encode character u'\xe8' in position 32: ordinal not in range(128)

eyed3:ERROR: 'ascii' codec can't encode character u'\xe8' in position 32: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 81, in walk
    handler.handleFile(os.path.abspath(path))
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/plugins/classic.py", line 457, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/home/pavel/.local/lib/python2.7/site-packages/eyed3/core.py", line 77, in load
    path = pathlib.Path(path)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 936, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 32: ordinal not in range(128)
```

**Comment by nicfit** [comment]
Many of the changes for 0.8 concerned the differences around Python2 vs Python3 unicode, so problems would not entirely surprise me, although this seems lilke like the problem could be how the filename is encoded vs. what the file\ system encoding is. This is evident by the stack trace exception originating in pathlib.Path, a standard library type.

If you send me the file (travis@pobox.com) I can dig deeper.

**Comment by von** [comment]
I'm seeing this error as well with 0.8 and the issue seems to be if there is any non-ascii character in the path, I get this error. The file itself doesn't matter. The following are all with the same file in three different places in the filesystem, the last one having some UTF-8 in the path.

```
% eyeD3 /tmp/01.La_vie_en_rose.mp3
/tmp/01.La_vie_en_rose.mp3                                         [ 2.88 MB ]
-------------------------------------------------------------------------------
Time: 03:09     MPEG1, Layer III        [ 128 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: La vie en rose
artist: Edith Piaf
album: Éternelle
album artist: None
recording date: 2000
track: 1/18             genre: Cabaret (id 65)
Comment: [Description: ] [Lang: eng]
DISCID:1b0c9c12
-------------------------------------------------------------------------------
% eyeD3 /Volumes/music/tmp/01.La_vie_en_rose.mp3
/Volumes/music/tmp/01.La_vie_en_rose.mp3                           [ 2.88 MB ]
-------------------------------------------------------------------------------
Time: 03:09     MPEG1, Layer III        [ 128 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: La vie en rose
artist: Edith Piaf
album: Éternelle
album artist: None
recording date: 2000
track: 1/18             genre: Cabaret (id 65)
Comment: [Description: ] [Lang: eng]
DISCID:1b0c9c12
-------------------------------------------------------------------------------
% eyeD3 /Volumes/music/mp3/Edith_Piaf/Éternelle/01.La_vie_en_rose.mp3
Uncaught exception: 'ascii' codec can't encode character u'\xc9' in position 30: ordinal not in range(128)

eyed3:ERROR: 'ascii' codec can't encode character u'\xc9' in position 30: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 81, in walk
    handler.handleFile(os.path.abspath(path))
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/plugins/classic.py", line 457, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/eyed3/core.py", line 77, in load
    path = pathlib.Path(path)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/pathlib.py", line 936, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/Users/von/.virtualenvs/cd-utils/lib/python2.7/site-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 30: ordinal not in range(128)
```

**Comment by nr1q** [comment]
Hello, I'm having the same issue regarding non-ascii characters in the filename. I tested other files (like "[C&SPL019] federsen.mp3") with no problem, but I get the same stack trace for a file like: "C.R.K. - флейты (Kramer Edit).mp3"

**Comment by nbroad1881** [comment]
I've also been trying to tag files with unicode in the path with no success.

**Comment by nicfit** [comment]
I have found no problems with unicode in paths if the file names use an encoding that matches:
``python -c 'import sys; print(sys.getfilesystemencoding())'``

I'm curious what the above reports for you all, please share...

eyeD3 now using pathlib.Path all over the place means more more conversion to unicode, whereas previously the raw bytes, however encoded, we used. There are likely steps eyeD3 you take to work around the problem, and I've toyed with tests and ``convmv`` to mimic, but it's a huge pain in the ass, and of little interest.  For example, 

```bash
$ python -c 'import sys; print(sys.getfilesystemencoding())'
utf-8

$ mkdir -p ./test/Éternelle/флейты
$ cp sample.mp3 ./test/Éternelle/флейты/test-ĀāĂăĄąĆćĈ.mp3
$ eyeD3 -a Rinôçerôse ./test/Éternelle/флейты/test-ĀāĂăĄąĆćĈ.mp3
$ eyeD3 ./test/Éternelle/флейты/test-ĀāĂăĄąĆćĈ.mp3
...ravis/devel/eyeD3/git/test/Éternelle/флейты/test-ĀāĂăĄąĆćĈ.mp3 [ 54.19 KB ]
-------------------------------------------------------------------------------
Time: 00:03	MPEG1, Layer III	[ 128 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: 
artist: Rinôçerôse
album: 
album artist: None
track: 		
-------------------------------------------------------------------------------
```

**Comment by von** [comment]
Here you go. Directory names copy and pasted from your comment above.

% eyeD3 --version
0.8.1
% python -c 'import sys; print(sys.getfilesystemencoding())'
utf-8
% cd /tmp
% mkdir Éternelle/флейты
% cp sample.mp3 Éternelle/флейты
% eyeD3 Éternelle/флейты/sample.mp3
Uncaught exception: 'ascii' codec can't encode character u'\xc9' in position 13: ordinal not in range(128)

eyed3:ERROR: 'ascii' codec can't encode character u'\xc9' in position 13: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 91, in walk
    handler.handleFile(os.path.abspath(path))
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/plugins/classic.py", line 457, in handleFile
    super(ClassicPlugin, self).handleFile(f, tag_version=parse_version)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/lib/python2.7/site-packages/eyed3/core.py", line 77, in load
    path = pathlib.Path(path)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/vendor/lib/python2.7/site-packages/pathlib.py", line 936, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/vendor/lib/python2.7/site-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/vendor/lib/python2.7/site-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/vendor/lib/python2.7/site-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/local/Cellar/eye-d3/0.8.1/libexec/vendor/lib/python2.7/site-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 13: ordinal not in range(128)

**Comment by nicfit** [comment]
Thanks @von, I was able to reproduce with Python2.7, it is not a problem for Python3. I have a fix coming.

**Comment by marcelpaulo** [comment]
I've just installed **0.8.3** with python **2.7.14**, and it seems that I'm hit with this same issue. I'm trying to rename files based on their tags:

`eyeD3 --rename '$track:num $title' .`

 This file failed:

```
/home/paulo/tmp/Atrium Musicæ de Madrid/Monodia Cortesana Medieval • Música Arábigo-Andaluza/06.mp3                                                                                   [ 1.95 MB ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 01:31	MPEG1, Layer III	[ ~177 kb/s @ 44100 Hz - Joint stereo ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.3:
title: Cardenal: Un sirventés
artist: Atrium Musicæ de Madrid
album: Monodia Cortesana Medieval • Música Arábigo-Andaluza
album artist: José Luis Ochoa de Olza, Orchesta Marroquí de Tetuán (Abdessadak Chkara)
recording date: 1969
eyed3.id3:WARNING: Non standard genre name: Medieval
track: 6		genre: Medieval (id None)
Comment: [Description: ] [Lang: XXX]
Trovadores catalanes y provenzales

```
Here's the stack:

```
eyed3:ERROR: 'ascii' codec can't encode character u'\xe9' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python2.7/site-packages/eyed3/main.py", line 279, in _main
    retval = mainFunc(args, config)
  File "/home/paulo/.local/lib/python2.7/site-packages/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/paulo/.local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 103, in walk
    handler.handleFile(f)
  File "/home/paulo/.local/lib/python2.7/site-packages/eyed3/plugins/classic.py", line 520, in handleFile
    self.audio_file.rename(name)
  File "/home/paulo/.local/lib/python2.7/site-packages/eyed3/core.py", line 205, in rename
    new_path = curr_path.parent / "{name}{ext}".format(**locals())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 23: ordinal not in range(128)

```

My version and system encoding:

```
paulo@monk:~/tmp/Atrium Musicæ de Madrid/Monodia Cortesana Medieval • Música Arábigo-Andaluza$ eyeD3 --version
0.8.3
paulo@monk:~/tmp/Atrium Musicæ de Madrid/Monodia Cortesana Medieval • Música Arábigo-Andaluza$ python -c 'import sys; print(sys.getfilesystemencoding())'
UTF-8
```

**EDIT:** Have just tried **0.8.3** with Python **3.6.3** and the file is correctly renamed
