### ISSUE TITLE
eyed3:ERROR: 'gbk' codec can't decode byte 0x90 in position 63: illegal multibyte sequence

### ISSUE THREAD

**Issue by Ly-zh0423** [nicfit/eyeD3#594]
eyed3 D:\Codes\Python\FFmpeg\1.m4a
我在终端中输入以上指令时报错如下
When I enter the above command in the terminal, the error is as follows
说是编码的问题，但是我查询了许多方法还是没有良好地解决方法，请问这个问题应该如何解决呢？
It is said that it is a coding problem, but I have queried many methods and still have no good solution. How can I solve this problem?
电脑配置如下：win7 64bit
python 3.8*
eyed3 0.96
The computer configuration is as follows: win7 64bit
python 3.8*
eyed3 0.96

错误如下：
The error is as follows：
Uncaught exception: 'gbk' codec can't decode byte 0x90 in position 63: illegal multibyte sequence
eyed3:ERROR: 'gbk' codec can't decode byte 0x90 in position 63: illegal multibyte sequence
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 273, in _ma
in
    args, _, config = parseCommandLine()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 232, in par
seCommandLine
    config = _loadConfig(args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 104, in _lo
adConfig
    config.read(config_file)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 63: illegal multibyte sequence
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 273, in _ma
in
    args, _, config = parseCommandLine()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 232, in par
seCommandLine
    config = _loadConfig(args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 104, in _lo
adConfig
    config.read(config_file)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 63: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\eyeD3.exe\__main__.py", line 7, in <module
>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\eyed3\main.py", line 289, in _ma
in
    if args.debug_pdb:
AttributeError: 'NoneType' object has no attribute 'debug_pdb'

**Comment by nicfit** [comment]
eyeD3 only supports mp3, not m4a

**Comment by Ly-zh0423** [comment]
Thank you very much!
