### ISSUE TITLE
EyeD3 fails to load file properly - what's wrong with it?

### ISSUE THREAD

**Issue by rexendevar** [nicfit/eyeD3#640]
I'm already kind of running out of patience, so I'm just going to paste the error and upload the file and have someone tell me what's going wrong here. 

```
audiofile = eyed3.load("/home/spyndling/bigboy4tb/Music imports/Taxman/AINOU/1-11 - そのいのち.mp3")
print(audiofile.tag.frame_set.keys())
Traceback (most recent call last):
  File "/home/spyndling/bigboy4tb/scripts/AutoLyricize/pain.py", line 7, in <module>
    audiofile = eyed3.load(folder + "/" + file)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/core.py", line 442, in load
    return mp3.Mp3AudioFile(path, tag_version)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/mp3/__init__.py", line 145, in __init__
    super().__init__(path)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/core.py", line 231, in __init__
    self._read()
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/mp3/__init__.py", line 151, in _read
    tag_found = self._tag.parse(file_obj, self._tag_version)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/id3/tag.py", line 99, in parse
    tag_found, padding = self._loadV2Tag(fileobj)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/id3/tag.py", line 131, in _loadV2Tag
    padding = self.frame_set.parse(fp, self.header,
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/id3/frames.py", line 1788, in parse
    frame = createFrame(tag_header, frame_header, data)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/id3/frames.py", line 1888, in createFrame
    frame.parse(data, frame_header)
  File "/home/spyndling/.local/lib/python3.10/site-packages/eyed3/id3/frames.py", line 1346, in parse
    self.channel_type = data[0]
IndexError: index out of range
```

https://drive.google.com/file/d/1VuxMJw5vFtOOwosHGOElJZYjLZsO8igp/view?usp=drive_link

No idea what's causing this. Every other file seems to work fine and it's not like my music player can't read the metadata either. I'm fairly sure at this point that it is a problem with the metadata of the file itself, but in the absence of eyed3, I don't have any way of checking. Would appreciate some answers.

**Comment by nicfit** [comment]
The issue is an invalid RVA2 frame. This patch works around it, and will appear in the next release.

```diff
iff --git a/eyed3/id3/frames.py b/eyed3/id3/frames.py
index b4e540c..f60d446 100644
--- a/eyed3/id3/frames.py
+++ b/eyed3/id3/frames.py
@@ -1382,10 +1382,14 @@ class RelVolAdjFrameV24(Frame):
         super().parse(data, frame_header)
         if self.header.version != ID3_V2_4:
             raise FrameException(f"Invalid frame version: {self.header.version}")
+        elif not data:
+            raise FrameException(f"Invalid frame data: empty")
 
         data = self.data
 
         self.identifier, data = data.split(b"\x00", maxsplit=1)
+        if not data:
+            raise FrameException(f"Invalid frame data: no channel type")
         self.channel_type = data[0]
         self._adjustment = bytes2signedInt16(data[1:3])
         if len(data) > 3:
```
